#!/bin/bash
# $Id: g++rom,v 1.2 2008-04-23 14:20:59 sybreon Exp $

# Compile using C++ pre-processor
mb-g++ \
-O2 \
-Wl,-defsym -Wl,_STACK_SIZE=0x400 \
-Wl,-defsym -Wl,_HEAP_SIZE=0x400 \
-mxl-soft-div -msoft-float \
-mxl-barrel-shift -mno-xl-soft-mul \
-Icc/ \
$@ \
-lc_m_bs -lm_m_bs \
-o rom.elf && \
echo "GCC=$?" && \

# echo the checksum
MD5=$(md5sum rom.elf | cut -c1-32) && \
echo "MD5=$MD5" && \

# Create a text listing of the compiled code
mb-objdump -DSCz rom.elf > rom.dump && \
echo "ASM=$?" && \

# Convert the ELF file to an SREC file
mb-objcopy -O srec rom.elf rom.srec && \
echo "OBJ=$?" && \

# Generate a Verilog VMEM file from the SREC file
srec_cat rom.srec -o ../sim/dump.vmem -vmem 32 && \
echo "HEX=$?" && \

# Cleanup code
rm rom.srec && \

# Say Cheeze!
echo "ROM generated"

# $Log: not supported by cvs2svn $
# Revision 1.1  2008/04/09 19:48:38  sybreon
# Added new C++ files
#