#!/bin/sh
# $Id: iversim,v 1.3 2007-11-09 20:50:51 sybreon Exp $
# $Log: not supported by cvs2svn $
# Revision 1.2  2007/11/05 10:59:31  sybreon
# Added random seed for simulation.
#
# Revision 1.1  2007/03/09 17:41:55  sybreon
# initial import
#
RANDOM=$(date +%s)
echo "parameter randseed = $RANDOM;" > random.v
iverilog $@ ../rtl/verilog/*.v && vvp -l iverilog.log a.out && rm a.out
