#!/bin/sh
# $Id: iversim,v 1.2 2007-11-05 10:59:31 sybreon Exp $
# $Log: not supported by cvs2svn $
# Revision 1.1  2007/03/09 17:41:55  sybreon
# initial import
#
RANDOM=$(date +%s)
echo "parameter randseed = $RANDOM;" > random.v
iverilog $@ ../rtl/verilog/*.v && vvp a.out && rm a.out
