#!/bin/bash
# $Id: iversim,v 1.7 2008-05-01 08:33:52 sybreon Exp $
# $Log: not supported by cvs2svn $
# Revision 1.6  2008/04/27 16:28:53  sybreon
# Added VCD2LXT functions.
#
# Revision 1.5  2007/12/11 00:44:30  sybreon
# Modified for AEMB2
#
# Revision 1.4  2007/11/30 17:08:30  sybreon
# Moved simulation kernel into code.
#
# Revision 1.3  2007/11/09 20:50:51  sybreon
# Added log output to iverilog.log
#
# Revision 1.2  2007/11/05 10:59:31  sybreon
# Added random seed for simulation.
#
# Revision 1.1  2007/03/09 17:41:55  sybreon
# initial import
#
RANDOM=$(date +%s)
echo "parameter randseed = $RANDOM;" > random.v
iverilog $@  -y../rtl/verilog/ -y./verilog/ && echo "VER=$?"
vvp -l iverilog.log a.out && echo "VVP=$?"
vcd2lxt2 dump.vcd dump.lxt && echo "LXT=$?"
rm *.vcd && rm a.out
